name: pixaby_tw
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  url_strategy: ^0.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true